version: 0.2
phases:
 install:
  runtime-versions:
   java: corretto8
  command:
   -aws cloudformation package --template-file template.yml --s3-bucket lambda-pipeline-bucket-akg --output-template-file template-export.yml
artifacts:
 type: zip
 files:
  - template.yml
  - template-export.yml
