version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.7
  command:
   -aws cloudformation package --template-file template.yaml --s3-bucket lambda-pipeline-bucket-akg --output-template-file outputSamTemplate.yaml
artifacts:
 type: zip
 files:
  - template.yaml
  - outputSamTemplate.yaml
