version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket lambda-pipeline-bucket-akg --output-template-file template-export.yml
artifacts:
  type: zip
  files:
    - template.yml
    - template-export.yml
